/*
Copyright: Funnel Metrics, LLC
*/
public class FunnelFilterWrapper{
        
    public String labelOne {get; set;}
    
    public String labelTwo {get; set;}
    
    public String labelThree {get; set;}
	
	public String labelFour {get; set;}  
    
    public String labelFive {get; set;}  
    
    public String labelSix {get; set;}  
    
    public String labelSeven {get; set;}  
    
    public String labelEight {get; set;}
    
    public String SelectedLevelOne { get;set;} 
    
    public String SelectedLevelTwo { get;set;} 
    
    public String SelectedLevelThree { get;set;}
    
    public String SelectedLevelFour { get;set;}
    
    public List<String> SelectedLevelFive { get;set;}
    
    public String SelectedLevelSix { get;set;}
    
    public String SelectedLevelSeven { get;set;}
    
    public String SelectedLevelEight { get;set;}
    
    public List<SelectOption> SelectedOptLevelFive { get;set;}
        
    public List<SelectOption> levelOne {get; set;}
    
    public List<SelectOption> levelTwo {get; set;}
    
    public List<SelectOption> levelThree{get; set;}
    
    public List<SelectOption> levelFour{get; set;}
    
    public List<SelectOption> levelFive{get; set;}
    
    public List<SelectOption> levelSix{get; set;}
    
    public List<SelectOption> levelSeven{get; set;}
    
    public List<SelectOption> levelEight{get; set;}
    
    public Id userId{get; set;}
    
    public Id srpId{get; set;}
    
    public Boolean isRep{get; set;}
    
    public Boolean disableLevelThree{get; set;}
    
    public Boolean disableLevelTwo{get; set;}
    
    public List<SelectOption> defaultLevelOne{get; set;}
    
    
    
}