/*--++---------------------+++----------------++++-------------------
Author:    Irfan Shaikh                     
Date:      13th, March 2019
Desc:      This controller is for making the call out to Trifecta APIs 
           for receiving the FS, QS, Important flag, and coeffecient
           evaluated by the model.
           
Copyright: Funnel Metrics, LLC
++-------------------+++++-----------++++--------------------------*/
public with sharing class FunnelGetApis {
   

}