/*
Copyright: Funnel Metrics, LLC
*/
public class FunnelReportingTableWrapper{
    
    public String rowName {get; set;}
    
    public String trend {get; set;}
        
    public String m1 {get; set;}
    
    public String m2 {get; set;}
    
    public String m3 {get; set;}
    
    public String m4 {get; set;}
    
    public String m5 {get; set;}
    
    public String m6 {get; set;}
    
    public String m7 {get; set;}
    
    public String m8 {get; set;}
    
    public String m9 {get; set;}
    
    public String m10 {get; set;}
    
    public String m11 {get; set;}
    
    public String m12 {get; set;}
    
    public Decimal decm1 {get; set;}
    
    public Decimal decm2 {get; set;}
    
    public Decimal decm3 {get; set;}
    
    public Decimal decm4 {get; set;}
    
    public Decimal decm5 {get; set;}
    
    public Decimal decm6 {get; set;}
    
    public Decimal decm7 {get; set;}
    
    public Decimal decm8 {get; set;}
    
    public Decimal decm9 {get; set;}
    
    public Decimal decm10 {get; set;}
    
    public Decimal decm11 {get; set;}
    
    public Decimal decm12 {get; set;}        
    
}