/*
Copyright: Funnel Metrics, LLC
*/
public class FunnelSalesProfileWrapper{
    
    public String name{get; set;}
    public String id{get; set;}
    public String title{get; set;}
    public String role{get; set;}
    public String salesManager{get; set;}
    public String territory{get; set;}
    public Decimal tenure{get; set;}
    public String startDate{get; set;}
    public Decimal score{get; set;}
    public Decimal scoreQual{get; set;}
    
    public String ytdCloseRate{get; set;}
    public Decimal ytdRevenue{get; set;}
    public Decimal annualQuota{get; set;}
    public Decimal winPercentage{get; set;}
    public Decimal salesPrice{get; set;}
    
    public Decimal ytdWonOpptys{get; set;}
    public Decimal currentActiveOpptys{get; set;}
    public Decimal annualQualifiedOpptys{get; set;}
    public Decimal quarterlyQualifiedOpptys{get; set;}
    public Decimal monthlyQualifiedOpptys{get; set;}    
    public Decimal winsForAnnualQuota{get; set;}
    public Decimal winsForQuarterlyQuota{get; set;}
    public Decimal winsForMonthlyQuota{get; set;}
    
    public Decimal leadConvPercentage{get; set;}
    public Decimal quarterlyLeadsForQuota{get; set;}
    public Decimal monthlyLeadsForQuota{get; set;}
    public Decimal dailyLeadsForQuota{get; set;}
    public Decimal leadsForWin{get; set;}
    public Decimal leadsForQualifiedOppty{get; set;}
    
    public String ytdQuotaPercentage{get; set;}
    public String ytdRevenueValue{get; set;}
    public String ytdQuotaValue{get; set;}
    public String winPercentageValue{get; set;}
    
    public String salesPriceValue{get; set;}
    
    public String annualQuotaValue{get; set;}
    public String quarterlyQuotaValue{get; set;}
    public String monthlyQuotaValue{get; set;}
    
    public String ytdWonOpptysValue{get; set;}
    public String currentActiveOpptysValue{get; set;}
    public String annualQualifiedOpptysValue{get; set;}
    public String quarterlyQualifiedOpptysValue{get; set;}
    public String monthlyQualifiedOpptysValue{get; set;}    
    public String winsForAnnualQuotaValue{get; set;}
    public String winsForQuarterlyQuotaValue{get; set;}
    public String winsForMonthlyQuotaValue{get; set;}
    
    public String leadConvPercentageValue{get; set;}
    public String ytdLeadsAdded{get; set;}
    public String quarterlyLeadsForQuotaValue{get; set;}
    public String monthlyLeadsForQuotaValue{get; set;}
    public String dailyLeadsForQuotaValue{get; set;}
    public String leadsForWinValue{get; set;}
    public String leadsForQualifiedOpptyValue{get; set;}
}