/*
Copyright: Funnel Metrics, LLC
*/
global with sharing class FunnelScheduleQualDataPull implements Schedulable {
   
   global void execute(SchedulableContext SC) {
      //try{
          
          
              //FunnelGetApis fp = new FunnelGetApis();
              //fp.getAndUpdateQualStats();
              /*FunnelQualDataPull m = new FunnelQualDataPull();      
              database.executebatch(m);*/
           
      /*}
      catch(Exception ex){
          FunnelTriggerBatchHelper.sendErrorMail(' FunnelScheduleQualDataPull '+ex.getMessage()+' '+ex.getStackTraceString()+ ' line number: '+ex.getLineNumber()+' cause '+ex.getCause());
      }*/
      
   }
}