/*
Copyright: Funnel Metrics, LLC
*/
global with sharing class FunnelScheduleQuantDataPull implements Schedulable {
   
   global void execute(SchedulableContext SC) {
      //try{
           
          
              //FunnelGetApis fp = new FunnelGetApis();
              //fp.getAndUpdateQuantStats();
               /*FunnelQuantDataPull m = new FunnelQuantDataPull();      
               database.executebatch(m);*/
          
      /*}
      catch(Exception ex){
          FunnelTriggerBatchHelper.sendErrorMail(' FunnelScheduleQuantDataPull '+ex.getMessage()+' '+ex.getStackTraceString()+ ' line number: '+ex.getLineNumber()+' cause '+ex.getCause());
      }*/
      
   }
}